/**
 * Excel 365 function catalog (US-English names).
 *
 * Signature notation:  NAME(required, [optional], [opt_a, opt_b], ...)
 *  - `[x]`          optional argument
 *  - `[a, b]`       optional group (must be supplied together)
 *  - trailing `...` the final argument / group may repeat (up to Excel's 255-argument limit)
 */
export type FunctionEntry = [signature: string, description: string];

export const CATALOG: Record<string, FunctionEntry[]> = {
  'Math & Trig': [
    ['ABS(number)', 'Returns the absolute value of a number.'],
    ['ACOS(number)', 'Returns the arccosine of a number, in radians.'],
    ['ACOSH(number)', 'Returns the inverse hyperbolic cosine of a number.'],
    ['ACOT(number)', 'Returns the arccotangent of a number, in radians.'],
    ['ACOTH(number)', 'Returns the inverse hyperbolic cotangent of a number.'],
    ['AGGREGATE(function_num, options, ref1, [ref2], ...)', 'Returns an aggregate (sum, average, etc.) with options to ignore errors and hidden rows.'],
    ['ARABIC(text)', 'Converts a Roman numeral to an Arabic number.'],
    ['ASIN(number)', 'Returns the arcsine of a number, in radians.'],
    ['ASINH(number)', 'Returns the inverse hyperbolic sine of a number.'],
    ['ATAN(number)', 'Returns the arctangent of a number, in radians.'],
    ['ATAN2(x_num, y_num)', 'Returns the arctangent from x and y coordinates.'],
    ['ATANH(number)', 'Returns the inverse hyperbolic tangent of a number.'],
    ['BASE(number, radix, [min_length])', 'Converts a number into a text representation in the given base.'],
    ['CEILING(number, significance)', 'Rounds a number up to the nearest multiple of significance.'],
    ['CEILING.MATH(number, [significance], [mode])', 'Rounds a number up to the nearest integer or multiple of significance.'],
    ['CEILING.PRECISE(number, [significance])', 'Rounds a number up to the nearest integer or multiple, regardless of sign.'],
    ['COMBIN(number, number_chosen)', 'Returns the number of combinations for a given number of items.'],
    ['COMBINA(number, number_chosen)', 'Returns the number of combinations with repetitions.'],
    ['COS(number)', 'Returns the cosine of an angle in radians.'],
    ['COSH(number)', 'Returns the hyperbolic cosine of a number.'],
    ['COT(number)', 'Returns the cotangent of an angle in radians.'],
    ['COTH(number)', 'Returns the hyperbolic cotangent of a number.'],
    ['CSC(number)', 'Returns the cosecant of an angle in radians.'],
    ['CSCH(number)', 'Returns the hyperbolic cosecant of an angle.'],
    ['DECIMAL(text, radix)', 'Converts a text representation of a number in a given base into a decimal number.'],
    ['DEGREES(angle)', 'Converts radians to degrees.'],
    ['EVEN(number)', 'Rounds a number up to the nearest even integer.'],
    ['EXP(number)', 'Returns e raised to the power of a number.'],
    ['FACT(number)', 'Returns the factorial of a number.'],
    ['FACTDOUBLE(number)', 'Returns the double factorial of a number.'],
    ['FLOOR(number, significance)', 'Rounds a number down, toward zero, to the nearest multiple of significance.'],
    ['FLOOR.MATH(number, [significance], [mode])', 'Rounds a number down to the nearest integer or multiple of significance.'],
    ['FLOOR.PRECISE(number, [significance])', 'Rounds a number down to the nearest integer or multiple, regardless of sign.'],
    ['GCD(number1, [number2], ...)', 'Returns the greatest common divisor.'],
    ['INT(number)', 'Rounds a number down to the nearest integer.'],
    ['ISO.CEILING(number, [significance])', 'Rounds a number up to the nearest integer or multiple of significance.'],
    ['LCM(number1, [number2], ...)', 'Returns the least common multiple.'],
    ['LN(number)', 'Returns the natural logarithm of a number.'],
    ['LOG(number, [base])', 'Returns the logarithm of a number to a specified base (default 10).'],
    ['LOG10(number)', 'Returns the base-10 logarithm of a number.'],
    ['MDETERM(array)', 'Returns the matrix determinant of an array.'],
    ['MINVERSE(array)', 'Returns the matrix inverse of an array.'],
    ['MMULT(array1, array2)', 'Returns the matrix product of two arrays.'],
    ['MOD(number, divisor)', 'Returns the remainder after a number is divided by a divisor.'],
    ['MROUND(number, multiple)', 'Returns a number rounded to the desired multiple.'],
    ['MULTINOMIAL(number1, [number2], ...)', 'Returns the multinomial of a set of numbers.'],
    ['MUNIT(dimension)', 'Returns the unit matrix for the specified dimension.'],
    ['ODD(number)', 'Rounds a number up to the nearest odd integer.'],
    ['PI()', 'Returns the value of pi, 3.14159265358979.'],
    ['POWER(number, power)', 'Returns the result of a number raised to a power.'],
    ['PRODUCT(number1, [number2], ...)', 'Multiplies all the numbers given as arguments.'],
    ['QUOTIENT(numerator, denominator)', 'Returns the integer portion of a division.'],
    ['RADIANS(angle)', 'Converts degrees to radians.'],
    ['RAND()', 'Returns a random number greater than or equal to 0 and less than 1.'],
    ['RANDARRAY([rows], [columns], [min], [max], [integer])', 'Returns an array of random numbers.'],
    ['RANDBETWEEN(bottom, top)', 'Returns a random integer between the numbers you specify.'],
    ['ROMAN(number, [form])', 'Converts an Arabic numeral to Roman, as text.'],
    ['ROUND(number, num_digits)', 'Rounds a number to a specified number of digits.'],
    ['ROUNDDOWN(number, num_digits)', 'Rounds a number down, toward zero.'],
    ['ROUNDUP(number, num_digits)', 'Rounds a number up, away from zero.'],
    ['SEC(number)', 'Returns the secant of an angle in radians.'],
    ['SECH(number)', 'Returns the hyperbolic secant of an angle.'],
    ['SEQUENCE(rows, [columns], [start], [step])', 'Returns an array of sequential numbers.'],
    ['SERIESSUM(x, n, m, coefficients)', 'Returns the sum of a power series based on a formula.'],
    ['SIGN(number)', 'Returns the sign of a number: 1, 0 or -1.'],
    ['SIN(number)', 'Returns the sine of an angle in radians.'],
    ['SINH(number)', 'Returns the hyperbolic sine of a number.'],
    ['SQRT(number)', 'Returns a positive square root.'],
    ['SQRTPI(number)', 'Returns the square root of (number * pi).'],
    ['SUBTOTAL(function_num, ref1, [ref2], ...)', 'Returns a subtotal in a list or database.'],
    ['SUM(number1, [number2], ...)', 'Adds all the numbers in a range of cells.'],
    ['SUMIF(range, criteria, [sum_range])', 'Adds the cells specified by a given criterion.'],
    ['SUMIFS(sum_range, criteria_range1, criteria1, [criteria_range2, criteria2], ...)', 'Adds the cells that meet multiple criteria.'],
    ['SUMPRODUCT(array1, [array2], ...)', 'Returns the sum of the products of corresponding array components.'],
    ['SUMSQ(number1, [number2], ...)', 'Returns the sum of the squares of the arguments.'],
    ['SUMX2MY2(array_x, array_y)', 'Returns the sum of the difference of squares of corresponding values in two arrays.'],
    ['SUMX2PY2(array_x, array_y)', 'Returns the sum of the sum of squares of corresponding values in two arrays.'],
    ['SUMXMY2(array_x, array_y)', 'Returns the sum of squares of differences of corresponding values in two arrays.'],
    ['TAN(number)', 'Returns the tangent of an angle in radians.'],
    ['TANH(number)', 'Returns the hyperbolic tangent of a number.'],
    ['TRUNC(number, [num_digits])', 'Truncates a number to an integer (or to the given digits).'],
  ],

  Statistical: [
    ['AVEDEV(number1, [number2], ...)', 'Returns the average of the absolute deviations of data points from their mean.'],
    ['AVERAGE(number1, [number2], ...)', 'Returns the average (arithmetic mean) of the arguments.'],
    ['AVERAGEA(value1, [value2], ...)', 'Returns the average of the arguments, including text and logical values.'],
    ['AVERAGEIF(range, criteria, [average_range])', 'Returns the average of the cells that meet a criterion.'],
    ['AVERAGEIFS(average_range, criteria_range1, criteria1, [criteria_range2, criteria2], ...)', 'Returns the average of the cells that meet multiple criteria.'],
    ['BETA.DIST(x, alpha, beta, cumulative, [A], [B])', 'Returns the beta cumulative distribution function.'],
    ['BETA.INV(probability, alpha, beta, [A], [B])', 'Returns the inverse of the beta cumulative distribution function.'],
    ['BINOM.DIST(number_s, trials, probability_s, cumulative)', 'Returns the individual term binomial distribution probability.'],
    ['BINOM.DIST.RANGE(trials, probability_s, number_s, [number_s2])', 'Returns the probability of a trial result using a binomial distribution.'],
    ['BINOM.INV(trials, probability_s, alpha)', 'Returns the smallest value for which the cumulative binomial distribution is at least a criterion.'],
    ['CHISQ.DIST(x, deg_freedom, cumulative)', 'Returns the left-tailed chi-squared distribution.'],
    ['CHISQ.DIST.RT(x, deg_freedom)', 'Returns the right-tailed chi-squared distribution.'],
    ['CHISQ.INV(probability, deg_freedom)', 'Returns the inverse of the left-tailed chi-squared distribution.'],
    ['CHISQ.INV.RT(probability, deg_freedom)', 'Returns the inverse of the right-tailed chi-squared distribution.'],
    ['CHISQ.TEST(actual_range, expected_range)', 'Returns the test for independence.'],
    ['CONFIDENCE.NORM(alpha, standard_dev, size)', 'Returns the confidence interval for a population mean (normal distribution).'],
    ['CONFIDENCE.T(alpha, standard_dev, size)', 'Returns the confidence interval for a population mean (Student t distribution).'],
    ['CORREL(array1, array2)', 'Returns the correlation coefficient between two data sets.'],
    ['COUNT(value1, [value2], ...)', 'Counts how many cells contain numbers.'],
    ['COUNTA(value1, [value2], ...)', 'Counts how many cells are not empty.'],
    ['COUNTBLANK(range)', 'Counts the empty cells in a range.'],
    ['COUNTIF(range, criteria)', 'Counts the cells that meet a criterion.'],
    ['COUNTIFS(criteria_range1, criteria1, [criteria_range2, criteria2], ...)', 'Counts the cells that meet multiple criteria.'],
    ['COVARIANCE.P(array1, array2)', 'Returns population covariance.'],
    ['COVARIANCE.S(array1, array2)', 'Returns sample covariance.'],
    ['DEVSQ(number1, [number2], ...)', 'Returns the sum of squares of deviations.'],
    ['EXPON.DIST(x, lambda, cumulative)', 'Returns the exponential distribution.'],
    ['F.DIST(x, deg_freedom1, deg_freedom2, cumulative)', 'Returns the left-tailed F probability distribution.'],
    ['F.DIST.RT(x, deg_freedom1, deg_freedom2)', 'Returns the right-tailed F probability distribution.'],
    ['F.INV(probability, deg_freedom1, deg_freedom2)', 'Returns the inverse of the left-tailed F probability distribution.'],
    ['F.INV.RT(probability, deg_freedom1, deg_freedom2)', 'Returns the inverse of the right-tailed F probability distribution.'],
    ['F.TEST(array1, array2)', 'Returns the result of an F-test.'],
    ['FISHER(x)', 'Returns the Fisher transformation.'],
    ['FISHERINV(y)', 'Returns the inverse of the Fisher transformation.'],
    ['FORECAST(x, known_y\'s, known_x\'s)', 'Calculates a future value along a linear trend (compatibility).'],
    ['FORECAST.ETS(target_date, values, timeline, [seasonality], [data_completion], [aggregation])', 'Calculates a future value using exponential triple smoothing (AAA).'],
    ['FORECAST.ETS.CONFINT(target_date, values, timeline, [confidence_level], [seasonality], [data_completion], [aggregation])', 'Returns a confidence interval for the forecast value.'],
    ['FORECAST.ETS.SEASONALITY(values, timeline, [data_completion], [aggregation])', 'Returns the length of the repetitive pattern Excel detects.'],
    ['FORECAST.ETS.STAT(values, timeline, statistic_type, [seasonality], [data_completion], [aggregation])', 'Returns a statistic of the exponential smoothing forecast.'],
    ['FORECAST.LINEAR(x, known_y\'s, known_x\'s)', 'Calculates a future value along a linear trend.'],
    ['FREQUENCY(data_array, bins_array)', 'Returns a frequency distribution as a vertical array.'],
    ['GAMMA(x)', 'Returns the gamma function value.'],
    ['GAMMA.DIST(x, alpha, beta, cumulative)', 'Returns the gamma distribution.'],
    ['GAMMA.INV(probability, alpha, beta)', 'Returns the inverse of the gamma cumulative distribution.'],
    ['GAMMALN(x)', 'Returns the natural logarithm of the gamma function.'],
    ['GAMMALN.PRECISE(x)', 'Returns the natural logarithm of the gamma function.'],
    ['GAUSS(z)', 'Returns 0.5 less than the standard normal cumulative distribution.'],
    ['GEOMEAN(number1, [number2], ...)', 'Returns the geometric mean.'],
    ['GROWTH(known_y\'s, [known_x\'s], [new_x\'s], [const])', 'Returns values along an exponential trend.'],
    ['HARMEAN(number1, [number2], ...)', 'Returns the harmonic mean.'],
    ['HYPGEOM.DIST(sample_s, number_sample, population_s, number_pop, cumulative)', 'Returns the hypergeometric distribution.'],
    ['INTERCEPT(known_y\'s, known_x\'s)', 'Returns the intercept of the linear regression line.'],
    ['KURT(number1, [number2], ...)', 'Returns the kurtosis of a data set.'],
    ['LARGE(array, k)', 'Returns the k-th largest value in a data set.'],
    ['LINEST(known_y\'s, [known_x\'s], [const], [stats])', 'Returns the parameters of a linear trend.'],
    ['LOGEST(known_y\'s, [known_x\'s], [const], [stats])', 'Returns the parameters of an exponential trend.'],
    ['LOGNORM.DIST(x, mean, standard_dev, cumulative)', 'Returns the lognormal distribution.'],
    ['LOGNORM.INV(probability, mean, standard_dev)', 'Returns the inverse of the lognormal cumulative distribution.'],
    ['MAX(number1, [number2], ...)', 'Returns the largest value in a set of values.'],
    ['MAXA(value1, [value2], ...)', 'Returns the largest value, including text and logical values.'],
    ['MAXIFS(max_range, criteria_range1, criteria1, [criteria_range2, criteria2], ...)', 'Returns the maximum value among cells that meet criteria.'],
    ['MEDIAN(number1, [number2], ...)', 'Returns the median of the given numbers.'],
    ['MIN(number1, [number2], ...)', 'Returns the smallest value in a set of values.'],
    ['MINA(value1, [value2], ...)', 'Returns the smallest value, including text and logical values.'],
    ['MINIFS(min_range, criteria_range1, criteria1, [criteria_range2, criteria2], ...)', 'Returns the minimum value among cells that meet criteria.'],
    ['MODE.MULT(number1, [number2], ...)', 'Returns a vertical array of the most frequently occurring values.'],
    ['MODE.SNGL(number1, [number2], ...)', 'Returns the most common value in a data set.'],
    ['NEGBINOM.DIST(number_f, number_s, probability_s, cumulative)', 'Returns the negative binomial distribution.'],
    ['NORM.DIST(x, mean, standard_dev, cumulative)', 'Returns the normal distribution.'],
    ['NORM.INV(probability, mean, standard_dev)', 'Returns the inverse of the normal cumulative distribution.'],
    ['NORM.S.DIST(z, cumulative)', 'Returns the standard normal distribution.'],
    ['NORM.S.INV(probability)', 'Returns the inverse of the standard normal cumulative distribution.'],
    ['PEARSON(array1, array2)', 'Returns the Pearson product-moment correlation coefficient.'],
    ['PERCENTILE.EXC(array, k)', 'Returns the k-th percentile, exclusive (0 < k < 1).'],
    ['PERCENTILE.INC(array, k)', 'Returns the k-th percentile, inclusive.'],
    ['PERCENTRANK.EXC(array, x, [significance])', 'Returns the rank of a value as an exclusive percentage.'],
    ['PERCENTRANK.INC(array, x, [significance])', 'Returns the rank of a value as an inclusive percentage.'],
    ['PERMUT(number, number_chosen)', 'Returns the number of permutations.'],
    ['PERMUTATIONA(number, number_chosen)', 'Returns the number of permutations with repetitions.'],
    ['PHI(x)', 'Returns the density of the standard normal distribution.'],
    ['POISSON.DIST(x, mean, cumulative)', 'Returns the Poisson distribution.'],
    ['PROB(x_range, prob_range, lower_limit, [upper_limit])', 'Returns the probability that values are between two limits.'],
    ['QUARTILE.EXC(array, quart)', 'Returns the quartile, exclusive.'],
    ['QUARTILE.INC(array, quart)', 'Returns the quartile, inclusive.'],
    ['RANK.AVG(number, ref, [order])', 'Returns the rank of a number in a list; ties get the average rank.'],
    ['RANK.EQ(number, ref, [order])', 'Returns the rank of a number in a list; ties get the top rank.'],
    ['RSQ(known_y\'s, known_x\'s)', 'Returns the square of the Pearson correlation coefficient.'],
    ['SKEW(number1, [number2], ...)', 'Returns the skewness of a distribution.'],
    ['SKEW.P(number1, [number2], ...)', 'Returns the skewness based on a population.'],
    ['SLOPE(known_y\'s, known_x\'s)', 'Returns the slope of the linear regression line.'],
    ['SMALL(array, k)', 'Returns the k-th smallest value in a data set.'],
    ['STANDARDIZE(x, mean, standard_dev)', 'Returns a normalized value.'],
    ['STDEV.P(number1, [number2], ...)', 'Calculates standard deviation based on the entire population.'],
    ['STDEV.S(number1, [number2], ...)', 'Estimates standard deviation based on a sample.'],
    ['STDEVA(value1, [value2], ...)', 'Estimates standard deviation of a sample, including text and logicals.'],
    ['STDEVPA(value1, [value2], ...)', 'Calculates standard deviation of a population, including text and logicals.'],
    ['STEYX(known_y\'s, known_x\'s)', 'Returns the standard error of the predicted y for each x in the regression.'],
    ['T.DIST(x, deg_freedom, cumulative)', 'Returns the left-tailed Student t-distribution.'],
    ['T.DIST.2T(x, deg_freedom)', 'Returns the two-tailed Student t-distribution.'],
    ['T.DIST.RT(x, deg_freedom)', 'Returns the right-tailed Student t-distribution.'],
    ['T.INV(probability, deg_freedom)', 'Returns the left-tailed inverse of the Student t-distribution.'],
    ['T.INV.2T(probability, deg_freedom)', 'Returns the two-tailed inverse of the Student t-distribution.'],
    ['T.TEST(array1, array2, tails, type)', 'Returns the probability associated with a Student t-test.'],
    ['TREND(known_y\'s, [known_x\'s], [new_x\'s], [const])', 'Returns values along a linear trend.'],
    ['TRIMMEAN(array, percent)', 'Returns the mean of the interior of a data set.'],
    ['VAR.P(number1, [number2], ...)', 'Calculates variance based on the entire population.'],
    ['VAR.S(number1, [number2], ...)', 'Estimates variance based on a sample.'],
    ['VARA(value1, [value2], ...)', 'Estimates variance of a sample, including text and logicals.'],
    ['VARPA(value1, [value2], ...)', 'Calculates variance of a population, including text and logicals.'],
    ['WEIBULL.DIST(x, alpha, beta, cumulative)', 'Returns the Weibull distribution.'],
    ['Z.TEST(array, x, [sigma])', 'Returns the one-tailed probability value of a z-test.'],
  ],

  Logical: [
    ['AND(logical1, [logical2], ...)', 'Returns TRUE if all arguments are TRUE.'],
    ['BYCOL(array, lambda)', 'Applies a LAMBDA to each column and returns an array of the results.'],
    ['BYROW(array, lambda)', 'Applies a LAMBDA to each row and returns an array of the results.'],
    ['FALSE()', 'Returns the logical value FALSE.'],
    ['IF(logical_test, [value_if_true], [value_if_false])', 'Returns one value if a condition is TRUE and another if it is FALSE.'],
    ['IFERROR(value, value_if_error)', 'Returns value_if_error if the expression is an error, otherwise the expression.'],
    ['IFNA(value, value_if_na)', 'Returns the value you specify if the expression resolves to #N/A.'],
    ['IFS(logical_test1, value_if_true1, [logical_test2, value_if_true2], ...)', 'Checks conditions in order and returns the value for the first TRUE one.'],
    ['ISOMITTED(argument)', 'Checks whether a LAMBDA argument was omitted.'],
    ['LAMBDA(parameter_or_calculation, ...)', 'Creates a custom, reusable function: LAMBDA(param1, param2, calculation).'],
    ['LET(name1, value1, calculation_or_name2, [value2, calculation_or_name3], ...)', 'Assigns names to calculation results, then evaluates a final calculation.'],
    ['MAKEARRAY(rows, cols, lambda)', 'Returns an array of the given size computed by a LAMBDA.'],
    ['MAP(array1, lambda_or_array2, ...)', 'Maps each value in one or more arrays to a new value using a LAMBDA.'],
    ['NOT(logical)', 'Reverses the logic of its argument.'],
    ['OR(logical1, [logical2], ...)', 'Returns TRUE if any argument is TRUE.'],
    ['REDUCE([initial_value], array, lambda)', 'Reduces an array to an accumulated value by applying a LAMBDA to each element.'],
    ['SCAN([initial_value], array, lambda)', 'Scans an array applying a LAMBDA and returns each intermediate value.'],
    ['SWITCH(expression, value1, result1, [value2, result2], ...)', 'Evaluates an expression against values and returns the matching result; a final unpaired argument is the default.'],
    ['TRUE()', 'Returns the logical value TRUE.'],
    ['XOR(logical1, [logical2], ...)', 'Returns a logical exclusive OR of all arguments.'],
  ],

  'Lookup & Reference': [
    ['ADDRESS(row_num, column_num, [abs_num], [a1], [sheet_text])', 'Returns a cell reference as text.'],
    ['AREAS(reference)', 'Returns the number of areas in a reference.'],
    ['CHOOSE(index_num, value1, [value2], ...)', 'Chooses a value from a list based on an index number.'],
    ['CHOOSECOLS(array, col_num1, [col_num2], ...)', 'Returns the specified columns from an array.'],
    ['CHOOSEROWS(array, row_num1, [row_num2], ...)', 'Returns the specified rows from an array.'],
    ['COLUMN([reference])', 'Returns the column number of a reference.'],
    ['COLUMNS(array)', 'Returns the number of columns in a reference or array.'],
    ['DROP(array, rows, [columns])', 'Excludes a number of rows or columns from the start or end of an array.'],
    ['EXPAND(array, rows, [columns], [pad_with])', 'Expands an array to the specified dimensions.'],
    ['FILTER(array, include, [if_empty])', 'Filters a range or array based on criteria you define.'],
    ['FORMULATEXT(reference)', 'Returns the formula at a reference as text.'],
    ['GETPIVOTDATA(data_field, pivot_table, [field1, item1], ...)', 'Returns data stored in a PivotTable report.'],
    ['GROUPBY(row_fields, values, function, [field_headers], [total_depth], [sort_order], [filter_array], [field_relationship])', 'Groups, aggregates, sorts and filters data by row fields.'],
    ['HLOOKUP(lookup_value, table_array, row_index_num, [range_lookup])', 'Looks in the top row of a table and returns the value in a given row.'],
    ['HSTACK(array1, [array2], ...)', 'Appends arrays horizontally, one after the other.'],
    ['HYPERLINK(link_location, [friendly_name])', 'Creates a shortcut that opens a document or web page.'],
    ['INDEX(array, row_num, [column_num], [area_num])', 'Returns a value or reference from within a table or range.'],
    ['INDIRECT(ref_text, [a1])', 'Returns the reference specified by a text string.'],
    ['LOOKUP(lookup_value, lookup_vector, [result_vector])', 'Looks up values in a vector or array.'],
    ['MATCH(lookup_value, lookup_array, [match_type])', 'Returns the relative position of an item in an array.'],
    ['OFFSET(reference, rows, cols, [height], [width])', 'Returns a reference offset from a given reference.'],
    ['PERCENTOF(subset, total)', 'Returns the share a subset represents of a total.'],
    ['PIVOTBY(row_fields, col_fields, values, function, [field_headers], [row_total_depth], [row_sort_order], [col_total_depth], [col_sort_order], [filter_array], [relative_to])', 'Groups, aggregates, sorts and filters data by row and column fields.'],
    ['ROW([reference])', 'Returns the row number of a reference.'],
    ['ROWS(array)', 'Returns the number of rows in a reference or array.'],
    ['RTD(progID, server, topic1, [topic2], ...)', 'Retrieves real-time data from a COM automation server.'],
    ['SORT(array, [sort_index], [sort_order], [by_col])', 'Sorts the contents of a range or array.'],
    ['SORTBY(array, by_array1, [sort_order1], [by_array2, sort_order2], ...)', 'Sorts a range or array based on the values in a corresponding range or array.'],
    ['TAKE(array, rows, [columns])', 'Returns a number of rows or columns from the start or end of an array.'],
    ['TOCOL(array, [ignore], [scan_by_column])', 'Returns the array as a single column.'],
    ['TOROW(array, [ignore], [scan_by_column])', 'Returns the array as a single row.'],
    ['TRANSPOSE(array)', 'Returns the transpose of an array.'],
    ['TRIMRANGE(range, [trim_rows], [trim_cols])', 'Trims blank rows and columns from the edges of a range.'],
    ['UNIQUE(array, [by_col], [exactly_once])', 'Returns the unique values from a range or array.'],
    ['VLOOKUP(lookup_value, table_array, col_index_num, [range_lookup])', 'Looks in the first column of a table and returns the value in a given column.'],
    ['VSTACK(array1, [array2], ...)', 'Appends arrays vertically, one after the other.'],
    ['WRAPCOLS(vector, wrap_count, [pad_with])', 'Wraps a row or column of values into columns after a set number of values.'],
    ['WRAPROWS(vector, wrap_count, [pad_with])', 'Wraps a row or column of values into rows after a set number of values.'],
    ['XLOOKUP(lookup_value, lookup_array, return_array, [if_not_found], [match_mode], [search_mode])', 'Searches a range or array for a match and returns the corresponding item from a second range.'],
    ['XMATCH(lookup_value, lookup_array, [match_mode], [search_mode])', 'Returns the relative position of an item in an array or range.'],
  ],

  Text: [
    ['ARRAYTOTEXT(array, [format])', 'Returns an array of text values from any specified range.'],
    ['ASC(text)', 'Changes full-width characters to half-width.'],
    ['BAHTTEXT(number)', 'Converts a number to Thai text with the baht suffix.'],
    ['CHAR(number)', 'Returns the character specified by the code number.'],
    ['CLEAN(text)', 'Removes all nonprintable characters from text.'],
    ['CODE(text)', 'Returns the numeric code of the first character in a text string.'],
    ['CONCAT(text1, [text2], ...)', 'Combines text from multiple ranges and/or strings.'],
    ['CONCATENATE(text1, [text2], ...)', 'Joins several text items into one text item.'],
    ['DBCS(text)', 'Changes half-width characters to full-width.'],
    ['DOLLAR(number, [decimals])', 'Converts a number to text using currency format.'],
    ['EXACT(text1, text2)', 'Checks whether two text values are identical (case-sensitive).'],
    ['FIND(find_text, within_text, [start_num])', 'Finds one text value within another (case-sensitive).'],
    ['FINDB(find_text, within_text, [start_num])', 'Finds one text value within another by bytes (case-sensitive).'],
    ['FIXED(number, [decimals], [no_commas])', 'Formats a number as text with a fixed number of decimals.'],
    ['LEFT(text, [num_chars])', 'Returns the leftmost characters from a text value.'],
    ['LEFTB(text, [num_bytes])', 'Returns the leftmost bytes from a text value.'],
    ['LEN(text)', 'Returns the number of characters in a text string.'],
    ['LENB(text)', 'Returns the number of bytes in a text string.'],
    ['LOWER(text)', 'Converts text to lowercase.'],
    ['MID(text, start_num, num_chars)', 'Returns characters from the middle of a text string.'],
    ['MIDB(text, start_num, num_bytes)', 'Returns bytes from the middle of a text string.'],
    ['NUMBERVALUE(text, [decimal_separator], [group_separator])', 'Converts text to a number in a locale-independent way.'],
    ['PHONETIC(reference)', 'Extracts the phonetic (furigana) characters from a text string.'],
    ['PROPER(text)', 'Capitalizes the first letter in each word of a text value.'],
    ['REGEXEXTRACT(text, pattern, [return_mode], [case_sensitivity])', 'Extracts text that matches a regular expression.'],
    ['REGEXREPLACE(text, pattern, replacement, [occurrence], [case_sensitivity])', 'Replaces text that matches a regular expression.'],
    ['REGEXTEST(text, pattern, [case_sensitivity])', 'Checks whether text matches a regular expression.'],
    ['REPLACE(old_text, start_num, num_chars, new_text)', 'Replaces characters within text.'],
    ['REPLACEB(old_text, start_num, num_bytes, new_text)', 'Replaces bytes within text.'],
    ['REPT(text, number_times)', 'Repeats text a given number of times.'],
    ['RIGHT(text, [num_chars])', 'Returns the rightmost characters from a text value.'],
    ['RIGHTB(text, [num_bytes])', 'Returns the rightmost bytes from a text value.'],
    ['SEARCH(find_text, within_text, [start_num])', 'Finds one text value within another (not case-sensitive, supports wildcards).'],
    ['SEARCHB(find_text, within_text, [start_num])', 'Finds one text value within another by bytes (not case-sensitive).'],
    ['SUBSTITUTE(text, old_text, new_text, [instance_num])', 'Substitutes new text for old text in a text string.'],
    ['T(value)', 'Converts its arguments to text.'],
    ['TEXT(value, format_text)', 'Formats a number and converts it to text.'],
    ['TEXTAFTER(text, delimiter, [instance_num], [match_mode], [match_end], [if_not_found])', 'Returns text that occurs after a given character or string.'],
    ['TEXTBEFORE(text, delimiter, [instance_num], [match_mode], [match_end], [if_not_found])', 'Returns text that occurs before a given character or string.'],
    ['TEXTJOIN(delimiter, ignore_empty, text1, [text2], ...)', 'Combines text from multiple ranges using a delimiter.'],
    ['TEXTSPLIT(text, col_delimiter, [row_delimiter], [ignore_empty], [match_mode], [pad_with])', 'Splits text into rows or columns using delimiters.'],
    ['TRIM(text)', 'Removes extra spaces from text, leaving single spaces between words.'],
    ['UNICHAR(number)', 'Returns the Unicode character for a number.'],
    ['UNICODE(text)', 'Returns the number (code point) for the first character of the text.'],
    ['UPPER(text)', 'Converts text to uppercase.'],
    ['VALUE(text)', 'Converts a text argument to a number.'],
    ['VALUETOTEXT(value, [format])', 'Returns text from any specified value.'],
  ],

  'Date & Time': [
    ['DATE(year, month, day)', 'Returns the serial number of a particular date.'],
    ['DATEDIF(start_date, end_date, unit)', 'Calculates the difference between two dates in days, months or years.'],
    ['DATEVALUE(date_text)', 'Converts a date in text form to a serial number.'],
    ['DAY(serial_number)', 'Converts a serial number to a day of the month.'],
    ['DAYS(end_date, start_date)', 'Returns the number of days between two dates.'],
    ['DAYS360(start_date, end_date, [method])', 'Calculates days between two dates based on a 360-day year.'],
    ['EDATE(start_date, months)', 'Returns the date a number of months before or after a start date.'],
    ['EOMONTH(start_date, months)', 'Returns the last day of the month a number of months away.'],
    ['HOUR(serial_number)', 'Converts a serial number to an hour.'],
    ['ISOWEEKNUM(date)', 'Returns the ISO week number of the year for a date.'],
    ['MINUTE(serial_number)', 'Converts a serial number to a minute.'],
    ['MONTH(serial_number)', 'Converts a serial number to a month.'],
    ['NETWORKDAYS(start_date, end_date, [holidays])', 'Returns the number of whole working days between two dates.'],
    ['NETWORKDAYS.INTL(start_date, end_date, [weekend], [holidays])', 'Returns working days between two dates using custom weekend parameters.'],
    ['NOW()', 'Returns the current date and time.'],
    ['SECOND(serial_number)', 'Converts a serial number to a second.'],
    ['TIME(hour, minute, second)', 'Returns the serial number of a particular time.'],
    ['TIMEVALUE(time_text)', 'Converts a time in text form to a serial number.'],
    ['TODAY()', 'Returns the current date.'],
    ['WEEKDAY(serial_number, [return_type])', 'Converts a serial number to a day of the week.'],
    ['WEEKNUM(serial_number, [return_type])', 'Converts a serial number to the week number of the year.'],
    ['WORKDAY(start_date, days, [holidays])', 'Returns the date a number of working days before or after a date.'],
    ['WORKDAY.INTL(start_date, days, [weekend], [holidays])', 'Returns a workday date using custom weekend parameters.'],
    ['YEAR(serial_number)', 'Converts a serial number to a year.'],
    ['YEARFRAC(start_date, end_date, [basis])', 'Returns the year fraction between two dates.'],
  ],

  Information: [
    ['CELL(info_type, [reference])', 'Returns information about the formatting, location or contents of a cell.'],
    ['ERROR.TYPE(error_val)', 'Returns a number corresponding to an error type.'],
    ['INFO(type_text)', 'Returns information about the current operating environment.'],
    ['ISBLANK(value)', 'Returns TRUE if the value is blank.'],
    ['ISERR(value)', 'Returns TRUE if the value is any error except #N/A.'],
    ['ISERROR(value)', 'Returns TRUE if the value is any error.'],
    ['ISEVEN(number)', 'Returns TRUE if the number is even.'],
    ['ISFORMULA(reference)', 'Returns TRUE if the reference is to a cell containing a formula.'],
    ['ISLOGICAL(value)', 'Returns TRUE if the value is a logical value.'],
    ['ISNA(value)', 'Returns TRUE if the value is #N/A.'],
    ['ISNONTEXT(value)', 'Returns TRUE if the value is not text.'],
    ['ISNUMBER(value)', 'Returns TRUE if the value is a number.'],
    ['ISODD(number)', 'Returns TRUE if the number is odd.'],
    ['ISREF(value)', 'Returns TRUE if the value is a reference.'],
    ['ISTEXT(value)', 'Returns TRUE if the value is text.'],
    ['N(value)', 'Returns a value converted to a number.'],
    ['NA()', 'Returns the error value #N/A.'],
    ['SHEET([value])', 'Returns the sheet number of the referenced sheet.'],
    ['SHEETS([reference])', 'Returns the number of sheets in a reference.'],
    ['STOCKHISTORY(stock, start_date, [end_date], [interval], [headers], [property0], ...)', 'Retrieves historical data about a financial instrument.'],
    ['TYPE(value)', 'Returns a number indicating the data type of a value.'],
  ],

  Financial: [
    ['ACCRINT(issue, first_interest, settlement, rate, par, frequency, [basis], [calc_method])', 'Returns accrued interest for a security that pays periodic interest.'],
    ['ACCRINTM(issue, settlement, rate, par, [basis])', 'Returns accrued interest for a security that pays interest at maturity.'],
    ['AMORDEGRC(cost, date_purchased, first_period, salvage, period, rate, [basis])', 'Returns depreciation for each accounting period (French system, degressive).'],
    ['AMORLINC(cost, date_purchased, first_period, salvage, period, rate, [basis])', 'Returns depreciation for each accounting period (French system, linear).'],
    ['COUPDAYBS(settlement, maturity, frequency, [basis])', 'Returns days from the start of the coupon period to the settlement date.'],
    ['COUPDAYS(settlement, maturity, frequency, [basis])', 'Returns the number of days in the coupon period containing settlement.'],
    ['COUPDAYSNC(settlement, maturity, frequency, [basis])', 'Returns days from the settlement date to the next coupon date.'],
    ['COUPNCD(settlement, maturity, frequency, [basis])', 'Returns the next coupon date after the settlement date.'],
    ['COUPNUM(settlement, maturity, frequency, [basis])', 'Returns the number of coupons payable between settlement and maturity.'],
    ['COUPPCD(settlement, maturity, frequency, [basis])', 'Returns the previous coupon date before the settlement date.'],
    ['CUMIPMT(rate, nper, pv, start_period, end_period, type)', 'Returns the cumulative interest paid between two periods.'],
    ['CUMPRINC(rate, nper, pv, start_period, end_period, type)', 'Returns the cumulative principal paid on a loan between two periods.'],
    ['DB(cost, salvage, life, period, [month])', 'Returns depreciation using the fixed-declining balance method.'],
    ['DDB(cost, salvage, life, period, [factor])', 'Returns depreciation using the double-declining balance method.'],
    ['DISC(settlement, maturity, pr, redemption, [basis])', 'Returns the discount rate for a security.'],
    ['DOLLARDE(fractional_dollar, fraction)', 'Converts a fractional dollar price to a decimal.'],
    ['DOLLARFR(decimal_dollar, fraction)', 'Converts a decimal dollar price to a fraction.'],
    ['DURATION(settlement, maturity, coupon, yld, frequency, [basis])', 'Returns the annual duration of a security with periodic interest.'],
    ['EFFECT(nominal_rate, npery)', 'Returns the effective annual interest rate.'],
    ['FV(rate, nper, pmt, [pv], [type])', 'Returns the future value of an investment.'],
    ['FVSCHEDULE(principal, schedule)', 'Returns the future value of a principal after a series of compound rates.'],
    ['INTRATE(settlement, maturity, investment, redemption, [basis])', 'Returns the interest rate for a fully invested security.'],
    ['IPMT(rate, per, nper, pv, [fv], [type])', 'Returns the interest payment for an investment for a given period.'],
    ['IRR(values, [guess])', 'Returns the internal rate of return for a series of cash flows.'],
    ['ISPMT(rate, per, nper, pv)', 'Calculates the interest paid during a specific period of an investment.'],
    ['MDURATION(settlement, maturity, coupon, yld, frequency, [basis])', 'Returns the modified Macaulay duration for a security.'],
    ['MIRR(values, finance_rate, reinvest_rate)', 'Returns the internal rate of return where positive and negative cash flows use different rates.'],
    ['NOMINAL(effect_rate, npery)', 'Returns the annual nominal interest rate.'],
    ['NPER(rate, pmt, pv, [fv], [type])', 'Returns the number of periods for an investment.'],
    ['NPV(rate, value1, [value2], ...)', 'Returns the net present value of an investment from a discount rate and future cash flows.'],
    ['ODDFPRICE(settlement, maturity, issue, first_coupon, rate, yld, redemption, frequency, [basis])', 'Returns the price per $100 face value of a security with an odd first period.'],
    ['ODDFYIELD(settlement, maturity, issue, first_coupon, rate, pr, redemption, frequency, [basis])', 'Returns the yield of a security with an odd first period.'],
    ['ODDLPRICE(settlement, maturity, last_interest, rate, yld, redemption, frequency, [basis])', 'Returns the price per $100 face value of a security with an odd last period.'],
    ['ODDLYIELD(settlement, maturity, last_interest, rate, pr, redemption, frequency, [basis])', 'Returns the yield of a security with an odd last period.'],
    ['PDURATION(rate, pv, fv)', 'Returns the number of periods required for an investment to reach a value.'],
    ['PMT(rate, nper, pv, [fv], [type])', 'Returns the periodic payment for an annuity.'],
    ['PPMT(rate, per, nper, pv, [fv], [type])', 'Returns the principal payment for an investment for a given period.'],
    ['PRICE(settlement, maturity, rate, yld, redemption, frequency, [basis])', 'Returns the price per $100 face value of a security that pays periodic interest.'],
    ['PRICEDISC(settlement, maturity, discount, redemption, [basis])', 'Returns the price per $100 face value of a discounted security.'],
    ['PRICEMAT(settlement, maturity, issue, rate, yld, [basis])', 'Returns the price per $100 face value of a security that pays interest at maturity.'],
    ['PV(rate, nper, pmt, [fv], [type])', 'Returns the present value of an investment.'],
    ['RATE(nper, pmt, pv, [fv], [type], [guess])', 'Returns the interest rate per period of an annuity.'],
    ['RECEIVED(settlement, maturity, investment, discount, [basis])', 'Returns the amount received at maturity for a fully invested security.'],
    ['RRI(nper, pv, fv)', 'Returns an equivalent interest rate for the growth of an investment.'],
    ['SLN(cost, salvage, life)', 'Returns straight-line depreciation for one period.'],
    ['SYD(cost, salvage, life, per)', 'Returns sum-of-years\' digits depreciation for a period.'],
    ['TBILLEQ(settlement, maturity, discount)', 'Returns the bond-equivalent yield for a Treasury bill.'],
    ['TBILLPRICE(settlement, maturity, discount)', 'Returns the price per $100 face value for a Treasury bill.'],
    ['TBILLYIELD(settlement, maturity, pr)', 'Returns the yield for a Treasury bill.'],
    ['VDB(cost, salvage, life, start_period, end_period, [factor], [no_switch])', 'Returns depreciation for any period using the variable declining balance method.'],
    ['XIRR(values, dates, [guess])', 'Returns the internal rate of return for irregularly timed cash flows.'],
    ['XNPV(rate, values, dates)', 'Returns the net present value for irregularly timed cash flows.'],
    ['YIELD(settlement, maturity, rate, pr, redemption, frequency, [basis])', 'Returns the yield on a security that pays periodic interest.'],
    ['YIELDDISC(settlement, maturity, pr, redemption, [basis])', 'Returns the annual yield for a discounted security.'],
    ['YIELDMAT(settlement, maturity, issue, rate, pr, [basis])', 'Returns the annual yield of a security that pays interest at maturity.'],
  ],

  Engineering: [
    ['BESSELI(x, n)', 'Returns the modified Bessel function In(x).'],
    ['BESSELJ(x, n)', 'Returns the Bessel function Jn(x).'],
    ['BESSELK(x, n)', 'Returns the modified Bessel function Kn(x).'],
    ['BESSELY(x, n)', 'Returns the Bessel function Yn(x).'],
    ['BIN2DEC(number)', 'Converts a binary number to decimal.'],
    ['BIN2HEX(number, [places])', 'Converts a binary number to hexadecimal.'],
    ['BIN2OCT(number, [places])', 'Converts a binary number to octal.'],
    ['BITAND(number1, number2)', 'Returns a bitwise AND of two numbers.'],
    ['BITLSHIFT(number, shift_amount)', 'Returns a number shifted left by the given number of bits.'],
    ['BITOR(number1, number2)', 'Returns a bitwise OR of two numbers.'],
    ['BITRSHIFT(number, shift_amount)', 'Returns a number shifted right by the given number of bits.'],
    ['BITXOR(number1, number2)', 'Returns a bitwise XOR of two numbers.'],
    ['COMPLEX(real_num, i_num, [suffix])', 'Converts real and imaginary coefficients into a complex number.'],
    ['CONVERT(number, from_unit, to_unit)', 'Converts a number from one measurement system to another.'],
    ['DEC2BIN(number, [places])', 'Converts a decimal number to binary.'],
    ['DEC2HEX(number, [places])', 'Converts a decimal number to hexadecimal.'],
    ['DEC2OCT(number, [places])', 'Converts a decimal number to octal.'],
    ['DELTA(number1, [number2])', 'Tests whether two values are equal.'],
    ['ERF(lower_limit, [upper_limit])', 'Returns the error function.'],
    ['ERF.PRECISE(x)', 'Returns the error function.'],
    ['ERFC(x)', 'Returns the complementary error function.'],
    ['ERFC.PRECISE(x)', 'Returns the complementary ERF function integrated between x and infinity.'],
    ['GESTEP(number, [step])', 'Tests whether a number is greater than a threshold value.'],
    ['HEX2BIN(number, [places])', 'Converts a hexadecimal number to binary.'],
    ['HEX2DEC(number)', 'Converts a hexadecimal number to decimal.'],
    ['HEX2OCT(number, [places])', 'Converts a hexadecimal number to octal.'],
    ['IMABS(inumber)', 'Returns the absolute value (modulus) of a complex number.'],
    ['IMAGINARY(inumber)', 'Returns the imaginary coefficient of a complex number.'],
    ['IMARGUMENT(inumber)', 'Returns the argument theta, an angle expressed in radians.'],
    ['IMCONJUGATE(inumber)', 'Returns the complex conjugate of a complex number.'],
    ['IMCOS(inumber)', 'Returns the cosine of a complex number.'],
    ['IMCOSH(inumber)', 'Returns the hyperbolic cosine of a complex number.'],
    ['IMCOT(inumber)', 'Returns the cotangent of a complex number.'],
    ['IMCSC(inumber)', 'Returns the cosecant of a complex number.'],
    ['IMCSCH(inumber)', 'Returns the hyperbolic cosecant of a complex number.'],
    ['IMDIV(inumber1, inumber2)', 'Returns the quotient of two complex numbers.'],
    ['IMEXP(inumber)', 'Returns the exponential of a complex number.'],
    ['IMLN(inumber)', 'Returns the natural logarithm of a complex number.'],
    ['IMLOG10(inumber)', 'Returns the base-10 logarithm of a complex number.'],
    ['IMLOG2(inumber)', 'Returns the base-2 logarithm of a complex number.'],
    ['IMPOWER(inumber, number)', 'Returns a complex number raised to an integer power.'],
    ['IMPRODUCT(inumber1, [inumber2], ...)', 'Returns the product of complex numbers.'],
    ['IMREAL(inumber)', 'Returns the real coefficient of a complex number.'],
    ['IMSEC(inumber)', 'Returns the secant of a complex number.'],
    ['IMSECH(inumber)', 'Returns the hyperbolic secant of a complex number.'],
    ['IMSIN(inumber)', 'Returns the sine of a complex number.'],
    ['IMSINH(inumber)', 'Returns the hyperbolic sine of a complex number.'],
    ['IMSQRT(inumber)', 'Returns the square root of a complex number.'],
    ['IMSUB(inumber1, inumber2)', 'Returns the difference of two complex numbers.'],
    ['IMSUM(inumber1, [inumber2], ...)', 'Returns the sum of complex numbers.'],
    ['IMTAN(inumber)', 'Returns the tangent of a complex number.'],
    ['OCT2BIN(number, [places])', 'Converts an octal number to binary.'],
    ['OCT2DEC(number)', 'Converts an octal number to decimal.'],
    ['OCT2HEX(number, [places])', 'Converts an octal number to hexadecimal.'],
  ],

  Database: [
    ['DAVERAGE(database, field, criteria)', 'Returns the average of selected database entries.'],
    ['DCOUNT(database, field, criteria)', 'Counts the cells that contain numbers in a database.'],
    ['DCOUNTA(database, field, criteria)', 'Counts nonblank cells in a database.'],
    ['DGET(database, field, criteria)', 'Extracts a single record that matches the criteria.'],
    ['DMAX(database, field, criteria)', 'Returns the maximum value from selected database entries.'],
    ['DMIN(database, field, criteria)', 'Returns the minimum value from selected database entries.'],
    ['DPRODUCT(database, field, criteria)', 'Multiplies the values in a field of matching records.'],
    ['DSTDEV(database, field, criteria)', 'Estimates standard deviation based on a sample of selected entries.'],
    ['DSTDEVP(database, field, criteria)', 'Calculates standard deviation based on the entire population of selected entries.'],
    ['DSUM(database, field, criteria)', 'Adds the numbers in the field column of matching records.'],
    ['DVAR(database, field, criteria)', 'Estimates variance based on a sample from selected entries.'],
    ['DVARP(database, field, criteria)', 'Calculates variance based on the entire population of selected entries.'],
  ],

  Web: [
    ['ENCODEURL(text)', 'Returns a URL-encoded string.'],
    ['FILTERXML(xml, xpath)', 'Returns specific data from XML content using an XPath.'],
    ['IMAGE(source, [alt_text], [sizing], [height], [width])', 'Returns an image from a source URL.'],
    ['WEBSERVICE(url)', 'Returns data from a web service.'],
  ],

  Cube: [
    ['CUBEKPIMEMBER(connection, kpi_name, kpi_property, [caption])', 'Returns a key performance indicator property from a cube.'],
    ['CUBEMEMBER(connection, member_expression, [caption])', 'Returns a member or tuple from the cube.'],
    ['CUBEMEMBERPROPERTY(connection, member_expression, property)', 'Returns the value of a member property in the cube.'],
    ['CUBERANKEDMEMBER(connection, set_expression, rank, [caption])', 'Returns the n-th, or ranked, member in a set.'],
    ['CUBESET(connection, set_expression, [caption], [sort_order], [sort_by])', 'Defines a calculated set of members or tuples.'],
    ['CUBESETCOUNT(set)', 'Returns the number of items in a set.'],
    ['CUBEVALUE(connection, [member_expression1], ...)', 'Returns an aggregated value from the cube.'],
  ],

  Compatibility: [
    ['BETADIST(x, alpha, beta, [A], [B])', 'Returns the beta cumulative distribution (use BETA.DIST).'],
    ['BETAINV(probability, alpha, beta, [A], [B])', 'Returns the inverse of the beta cumulative distribution (use BETA.INV).'],
    ['BINOMDIST(number_s, trials, probability_s, cumulative)', 'Returns the binomial distribution probability (use BINOM.DIST).'],
    ['CHIDIST(x, deg_freedom)', 'Returns the right-tailed chi-squared distribution (use CHISQ.DIST.RT).'],
    ['CHIINV(probability, deg_freedom)', 'Returns the inverse of the right-tailed chi-squared distribution (use CHISQ.INV.RT).'],
    ['CHITEST(actual_range, expected_range)', 'Returns the test for independence (use CHISQ.TEST).'],
    ['CONFIDENCE(alpha, standard_dev, size)', 'Returns the confidence interval for a population mean (use CONFIDENCE.NORM).'],
    ['COVAR(array1, array2)', 'Returns covariance (use COVARIANCE.P).'],
    ['CRITBINOM(trials, probability_s, alpha)', 'Returns the smallest value for which the cumulative binomial distribution is at least a criterion (use BINOM.INV).'],
    ['EXPONDIST(x, lambda, cumulative)', 'Returns the exponential distribution (use EXPON.DIST).'],
    ['FDIST(x, deg_freedom1, deg_freedom2)', 'Returns the right-tailed F distribution (use F.DIST.RT).'],
    ['FINV(probability, deg_freedom1, deg_freedom2)', 'Returns the inverse of the right-tailed F distribution (use F.INV.RT).'],
    ['FTEST(array1, array2)', 'Returns the result of an F-test (use F.TEST).'],
    ['GAMMADIST(x, alpha, beta, cumulative)', 'Returns the gamma distribution (use GAMMA.DIST).'],
    ['GAMMAINV(probability, alpha, beta)', 'Returns the inverse of the gamma cumulative distribution (use GAMMA.INV).'],
    ['HYPGEOMDIST(sample_s, number_sample, population_s, number_pop)', 'Returns the hypergeometric distribution (use HYPGEOM.DIST).'],
    ['LOGINV(probability, mean, standard_dev)', 'Returns the inverse of the lognormal cumulative distribution (use LOGNORM.INV).'],
    ['LOGNORMDIST(x, mean, standard_dev)', 'Returns the cumulative lognormal distribution (use LOGNORM.DIST).'],
    ['MODE(number1, [number2], ...)', 'Returns the most common value in a data set (use MODE.SNGL).'],
    ['NEGBINOMDIST(number_f, number_s, probability_s)', 'Returns the negative binomial distribution (use NEGBINOM.DIST).'],
    ['NORMDIST(x, mean, standard_dev, cumulative)', 'Returns the normal cumulative distribution (use NORM.DIST).'],
    ['NORMINV(probability, mean, standard_dev)', 'Returns the inverse of the normal cumulative distribution (use NORM.INV).'],
    ['NORMSDIST(z)', 'Returns the standard normal cumulative distribution (use NORM.S.DIST).'],
    ['NORMSINV(probability)', 'Returns the inverse of the standard normal cumulative distribution (use NORM.S.INV).'],
    ['PERCENTILE(array, k)', 'Returns the k-th percentile (use PERCENTILE.INC).'],
    ['PERCENTRANK(array, x, [significance])', 'Returns the percentage rank of a value (use PERCENTRANK.INC).'],
    ['POISSON(x, mean, cumulative)', 'Returns the Poisson distribution (use POISSON.DIST).'],
    ['QUARTILE(array, quart)', 'Returns the quartile of a data set (use QUARTILE.INC).'],
    ['RANK(number, ref, [order])', 'Returns the rank of a number in a list (use RANK.EQ).'],
    ['STDEV(number1, [number2], ...)', 'Estimates standard deviation based on a sample (use STDEV.S).'],
    ['STDEVP(number1, [number2], ...)', 'Calculates standard deviation of a population (use STDEV.P).'],
    ['TDIST(x, deg_freedom, tails)', 'Returns the Student t-distribution (use T.DIST.2T or T.DIST.RT).'],
    ['TINV(probability, deg_freedom)', 'Returns the two-tailed inverse of the Student t-distribution (use T.INV.2T).'],
    ['TTEST(array1, array2, tails, type)', 'Returns the probability associated with a Student t-test (use T.TEST).'],
    ['VAR(number1, [number2], ...)', 'Estimates variance based on a sample (use VAR.S).'],
    ['VARP(number1, [number2], ...)', 'Calculates variance of a population (use VAR.P).'],
    ['WEIBULL(x, alpha, beta, cumulative)', 'Returns the Weibull distribution (use WEIBULL.DIST).'],
    ['ZTEST(array, x, [sigma])', 'Returns the one-tailed probability value of a z-test (use Z.TEST).'],
  ],
};
